var simplemaps_countrymap_mapdata = {
  main_settings: {
    // General settings
    width: "responsive", //'700' or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    
    // State defaults
    state_description: "State description",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "no",
    
    // Location defaults
    location_description: "Location description",
    location_url: "",
    location_color: "black",
    location_opacity: 0.5,
    location_hover_opacity: 1,
    location_size: 50,
    location_type: "image",
    location_image_source: "./countrymap/map_images/",
    location_border_color: "#FFFFFF",
    location_border: "no",
    location_hover_border: "no",
    all_locations_inactive: "no",
    all_locations_hidden: "no",
    
    // Label defaults
    label_color: "#ffffff",
    label_hover_color: "#ffffff",
    label_size: 16,
    label_font: "Poppis",
    label_display: "no",
    label_scale: "no",
    hide_labels: "no",
    hide_eastern_labels: "no",
   
    // Zoom settings
    zoom: "no",
    manual_zoom: "no",
    back_image: "no",
    initial_back: "no",
    initial_zoom: "no",
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "no",
    zoom_percentage: "no",
    zoom_time: "no",
    
    // Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Poppis, sans-serif",
    popup_nocss: "no",
    
    // Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "no",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "https://teiacrm.com/",
    popups: "detect",
    state_image_url: "",
    state_image_position: "",
    location_image_url: './countrymap/map_images/frog.png',
  },
  state_specific: {
    //BRAC: { name: "Acre" },
    BRAL: { name: "Alagoas", color: "#5fcc96" },
    BRAM: { name: "Amazonas", color: "#5fcc96" },
    //BRAP: { name: "Amapá", color: "#2B53A0" },
    BRBA: { name: "Bahia", color: "#5fcc96" },
    BRCE: { name: "Ceará", color: "#5fcc96" },
    //BRDF: { name: "Distrito Federal", color: "#2B53A0"},
    //BRES: { name: "Espírito Santo", color: "#2B53A0"},
    BRGO: { name: "Goiás", color: "#5fcc96" },
    //BRMA: { name: "Maranhão", color: "#2B53A0"},
    BRMG: { name: "Minas Gerais", color: "#5fcc96"},
    BRMS: { name: "Mato Grosso do Sul", color: "#5fcc96" },
    BRMT: { name: "Mato Grosso", color: "#5fcc96" },
    //BRPA: { name: "Pará", color: "#2B53A0" },
    BRPB: { name: "Paraíba", color: "#5fcc96" },
    //BRPE: { name: "Pernambuco", color: "#2B53A0" },
    BRPI: { name: "Piauí", color: "#5fcc96" },
    //BRPR: { name: "Paraná", color: "#2B53A0"},
    //BRRJ: { name: "Rio de Janeiro" , color: "blue" },
    BRRN: { name: "Rio Grande do Norte", color: "#5fcc96" },
    //BRRO: { name: "Rondônia", color: "#2B53A0"},
    //BRRR: { name: "Roraima", color: "#2B53A0"},
    BRRS: { name: "Rio Grande do Sul", color: "#5fcc96"},
    BRSC: { name: "Santa Catarina", color: "#5fcc96" },
    //BRSE: { name: "Sergipe", color: "#2B53A0"},
    BRSP: { name: "São Paulo", color: "#5fcc96" },
    BRTO: { name: "Tocantins", color: "#5fcc96"}
  },
  locations: {
    "0": { name: "Brasília", lat: "-15.783333", lng: "-47.916667", description: "Goiás" },
    "1": { name: "Natal", lat: "-5.7945", lng: "-35.211", description: "Sede do TEIA CRM - +4 Lojas Usando" },
    "2": { name: "Vitória da Conquista", lat: "-14.8615", lng: "-40.8448", description: "Bahia"},
    "3": { name: "Salvador", lat: "-12.9714", lng: "-38.5014", description: "Bahia"},
    "4": { name: "Fortaleza", lat: "-3.7172", lng: "-38.5434", description: "Ceará"},
    "5": { name: "Belo Horizonte", lat: "-19.9167", lng: "-43.9345", description: "Minas Gerais - +4 Lojas usando" },
    "6": { name: "Teresina", lat: "-5.0919", lng: "-42.8034", description: "Piauí" },
    //"7": { name: "João Pessoa", lat: "-7.115", lng: "-34.8631", description: "Pernambuco" },
    "8": { name: "Manaus", lat: "-3.1019", lng: "-60.025", description: "Amazonas - +2 Lojas Usam" },
    "9": { name: "Maceió", lat: "-9.6659", lng: "-35.735", description: "Alagoas" },
    "10": { name: "Cuiabá", lat: "-15.601", lng: "-56.0979", description: "Mato Grosso"},
    "11": { name: "São Paulo", lat: "-23.5505", lng: "-46.6333", description: "São Paulo" },
    //"12": { name: "Bom Jesus", lat: "-9.0741", lng: "-44.3579", description: "Ceará" },
    "13": { name: "Fortaleza", lat: "-3.71722", lng: "-38.5434", description: "Ceará - +5 Lojas usando" },
    //"13": { name: "Rio Branco", lat: "-9.9781", lng: "-67.8102", description: "Acre" },
    "14": { name: "Campo Grande", lat: "-20.4697", lng: "-54.6201", description: "Mato Grosso do Sul" },
   //"15": { name: "Macapá", lat: "0.0355", lng: "-51.0705", description: "Amapá" },
    "16": { name: "Florianópolis", lat: "-27.5954", lng: "-48.548", description: "Santa Catarina" },
    "17": { name: "Porto Alegre", lat: "-30.0346", lng: "-51.2177", description: "Rio Grande do Sul - 2 Lojas usam" },
    "18": { name: "Palmas", lat: "-10.1831", lng: "-48.3336", description: "Tocantins"},
    //"19": { name: "Belém", lat: "-1.4558", lng: "-48.5044", description: "Pará"},
    "20": { name: "Recife", lat: "-8.0476", lng: "-34.877", description: "Pernambuco" },
    //"21": { name: "Aracaju", lat: "-10.9472", lng: "-37.0731", description: "Sergipe" },
    //"22": { name: "Boa Vista", lat: "2.8235", lng: "-60.6758", description: "Roraima"},
    //"23": { name: "Porto Velho", lat: "-8.7608", lng: "-63.9039", description: "Rondônia" },
    //"24": { name: "Rio de Janeiro", lat: "-22.9083", lng: "-43.1964", description: "Rio de Janeiro" },
    //"25": { name: "São Luís", lat: "-2.5307", lng: "-44.3068", description: "Maranhão"},
    "26": { name: "Goiânia", lat: "-16.6869", lng: "-49.2643", description: "Goiás" },
    //"27": { name: "Vitória", lat: "-20.3155", lng: "-40.3128", description: "Espírito Santo" },
    "28": { name: "Curitiba", lat: "-25.4284", lng: "-49.2733", description: "Paraná" },
    "29": { name: "Teresina", lat: "-5.0919", lng: "-42.8034", description: "Piauí" }
  },
  labels: {},
  regions: {},
  legend: {
    entries: []
  }
};

